# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/DATA/vivado_project/0TEST/minist_cnn/minist_cnn/minist_cnn.srcs/sources_1/ip/B_conv1/B_conv1.xci
# IP: The module: 'B_conv1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/DATA/vivado_project/0TEST/minist_cnn/minist_cnn/minist_cnn.srcs/sources_1/ip/B_conv1/B_conv1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'B_conv1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/DATA/vivado_project/0TEST/minist_cnn/minist_cnn/minist_cnn.srcs/sources_1/ip/B_conv1/B_conv1.xci
# IP: The module: 'B_conv1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/DATA/vivado_project/0TEST/minist_cnn/minist_cnn/minist_cnn.srcs/sources_1/ip/B_conv1/B_conv1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'B_conv1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
