# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/DATA/vivado_project/0TEST/minist_cnn/minist_cnn/minist_cnn.srcs/sources_1/ip/fifo_generator_200/fifo_generator_200.xci
# IP: The module: 'fifo_generator_200' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/DATA/vivado_project/0TEST/minist_cnn/minist_cnn/minist_cnn.srcs/sources_1/ip/fifo_generator_200/fifo_generator_200.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_200'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/DATA/vivado_project/0TEST/minist_cnn/minist_cnn/minist_cnn.srcs/sources_1/ip/fifo_generator_200/fifo_generator_200_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_200'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/DATA/vivado_project/0TEST/minist_cnn/minist_cnn/minist_cnn.srcs/sources_1/ip/fifo_generator_200/fifo_generator_200.xci
# IP: The module: 'fifo_generator_200' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/DATA/vivado_project/0TEST/minist_cnn/minist_cnn/minist_cnn.srcs/sources_1/ip/fifo_generator_200/fifo_generator_200.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_200'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/DATA/vivado_project/0TEST/minist_cnn/minist_cnn/minist_cnn.srcs/sources_1/ip/fifo_generator_200/fifo_generator_200_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_200'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
