# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/DATA/vivado_project/0TEST/minist_cnn/minist_cnn/minist_cnn.srcs/sources_1/ip/picture_784/picture_784.xci
# IP: The module: 'picture_784' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/DATA/vivado_project/0TEST/minist_cnn/minist_cnn/minist_cnn.srcs/sources_1/ip/picture_784/picture_784_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'picture_784'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/DATA/vivado_project/0TEST/minist_cnn/minist_cnn/minist_cnn.srcs/sources_1/ip/picture_784/picture_784.xci
# IP: The module: 'picture_784' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/DATA/vivado_project/0TEST/minist_cnn/minist_cnn/minist_cnn.srcs/sources_1/ip/picture_784/picture_784_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'picture_784'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
